name: Run Code Checks
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install globals @eslint/js @eslint/eslintrc -D && npm install eslint -g
    - name: Install and run ESLint
      run: eslint . --quiet
    - name: Run Mocha Tests
      run: npm install && npm test
